# Generated by Django 5.1.2 on 2024-11-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='skill_level',
            new_name='ExperienceLevel',
        ),
    ]
