# Generated by Django 5.1.2 on 2024-11-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_skill_level_userprofile_experiencelevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ExperienceLevel',
            new_name='experience_level',
        ),
    ]
