# Generated by Django 5.1.2 on 2025-01-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_strava_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activities_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
    ]
